// Distritos principales por región en Perú
export const DISTRICTS_BY_REGION: Record<string, string[]> = {
  'Amazonas': ['Chachapoyas', 'Bagua', 'Bagua Grande', 'Rodríguez de Mendoza', 'Utcubamba'],
  'Áncash': ['Huaraz', 'Chimbote', 'Casma', 'Huarmey', 'Caraz', 'Carhuaz', 'Yungay'],
  'Apurímac': ['Abancay', 'Andahuaylas', 'Chincheros', 'Antabamba', 'Grau'],
  'Arequipa': ['Arequipa', 'Cayma', 'Cerro Colorado', 'Characato', 'Jacobo Hunter', 'José Luis Bustamante y Rivero', 'Mariano Melgar', 'Miraflores', 'Paucarpata', 'Sachaca', 'Socabaya', 'Tiabaya', 'Yanahuara', 'Yura', 'Camaná', 'Mollendo', 'Islay'],
  'Ayacucho': ['Ayacucho', 'Huamanga', 'Huanta', 'San Miguel', 'La Mar', 'Cangallo'],
  'Cajamarca': ['Cajamarca', 'Jaén', 'Chota', 'Cutervo', 'Bambamarca', 'San Ignacio'],
  'Callao': ['Callao', 'Bellavista', 'Carmen de la Legua Reynoso', 'La Perla', 'La Punta', 'Ventanilla'],
  'Cusco': ['Cusco', 'Wanchaq', 'Santiago', 'San Sebastián', 'San Jerónimo', 'Sicuani', 'Urubamba', 'Calca', 'Pisac', 'Ollantaytambo'],
  'Huancavelica': ['Huancavelica', 'Lircay', 'Acobamba', 'Tayacaja', 'Pampas'],
  'Huánuco': ['Huánuco', 'Amarilis', 'Pillco Marca', 'Tingo María', 'Leoncio Prado', 'Huamalíes'],
  'Ica': ['Ica', 'Chincha Alta', 'Pisco', 'Nazca', 'Palpa', 'Parcona', 'Subtanjalla'],
  'Junín': ['Huancayo', 'El Tambo', 'Chilca', 'Tarma', 'La Oroya', 'Jauja', 'Concepción', 'Satipo', 'Chanchamayo'],
  'La Libertad': ['Trujillo', 'La Esperanza', 'El Porvenir', 'Florencia de Mora', 'Huanchaco', 'Laredo', 'Moche', 'Salaverry', 'Víctor Larco Herrera', 'Chepén', 'Pacasmayo', 'Guadalupe', 'Ascope'],
  'Lambayeque': ['Chiclayo', 'José Leonardo Ortiz', 'La Victoria', 'Lambayeque', 'Ferreñafe', 'Monsefú', 'Pimentel', 'Santa Rosa', 'Pomalca'],
  'Lima Province': ['Lima', 'Miraflores', 'San Isidro', 'Surco', 'La Molina', 'San Borja', 'Barranco', 'San Miguel', 'Jesús María', 'Lince', 'Magdalena del Mar', 'Pueblo Libre', 'Breña'],
  'Lima': ['Lima', 'Ate', 'Barranco', 'Breña', 'Carabayllo', 'Chaclacayo', 'Chorrillos', 'Cieneguilla', 'Comas', 'El Agustino', 'Independencia', 'Jesús María', 'La Molina', 'La Victoria', 'Lince', 'Los Olivos', 'Lurigancho', 'Lurín', 'Magdalena del Mar', 'Miraflores', 'Pachacámac', 'Pucusana', 'Pueblo Libre', 'Puente Piedra', 'Punta Hermosa', 'Punta Negra', 'Rímac', 'San Bartolo', 'San Borja', 'San Isidro', 'San Juan de Lurigancho', 'San Juan de Miraflores', 'San Luis', 'San Martín de Porres', 'San Miguel', 'Santa Anita', 'Santa María del Mar', 'Santa Rosa', 'Santiago de Surco', 'Surquillo', 'Villa El Salvador', 'Villa María del Triunfo', 'Huacho', 'Barranca', 'Huaral', 'Cañete', 'Huaura'],
  'Loreto': ['Iquitos', 'Punchana', 'Belén', 'San Juan Bautista', 'Yurimaguas', 'Nauta', 'Requena'],
  'Madre de Dios': ['Puerto Maldonado', 'Tambopata', 'Manu', 'Tahuamanu'],
  'Moquegua': ['Moquegua', 'Ilo', 'Mariscal Nieto', 'Sánchez Cerro'],
  'Pasco': ['Cerro de Pasco', 'Yanacancha', 'Chaupimarca', 'Oxapampa', 'Villa Rica'],
  'Piura': ['Piura', 'Castilla', 'Catacaos', 'Sullana', 'Paita', 'Talara', 'Sechura', 'Chulucanas', 'Tambogrande'],
  'Puno': ['Puno', 'Juliaca', 'Ilave', 'Yunguyo', 'Azángaro', 'Ayaviri', 'Desaguadero'],
  'San Martín': ['Moyobamba', 'Tarapoto', 'Morales', 'Juanjuí', 'Rioja', 'Tocache', 'Bellavista'],
  'Tacna': ['Tacna', 'Alto de la Alianza', 'Ciudad Nueva', 'Coronel Gregorio Albarracín Lanchipa', 'Pocollay'],
  'Tumbes': ['Tumbes', 'Zarumilla', 'Contralmirante Villar', 'Zorritos', 'Aguas Verdes'],
  'Ucayali': ['Pucallpa', 'Callería', 'Yarinacocha', 'Manantay', 'Atalaya', 'Padre Abad'],
};
