ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "packedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "packedById" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "packingNotes" TEXT;
