-- AlterTable
ALTER TABLE "Coupon" ADD COLUMN     "division" "Division" NOT NULL DEFAULT 'JUGUETERIA',
ADD COLUMN     "expiresAt" TIMESTAMP(3),
ADD COLUMN     "maxUses" INTEGER,
ADD COLUMN     "startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "usedCount" INTEGER NOT NULL DEFAULT 0;
